# Site settings
title: "Brittany Anderson"
email: 
description: ""
baseurl: ""
url: "http://bmanders716.github.io"
title_description: ""
title_image: ""
google_analytics: ""
disqus_account: 
github_repository: https://github.com/bmanders716/bmanders716.github.io
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  bmanders716
linkedin_link: 
google_plus_link: 
stackoverflow_link: 

# Footer
footer_left: ""
footer_right: ""

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
